### ISSUE TITLE
Large amount of options 

### ISSUE THREAD

**Issue by flaviodelgrosso** [jacobworrel/react-windowed-select#39]
Hi Jacob and all contributors. Thanks for your nice and interesting work. I'd like to ask if there's in program or if eventually possible to optimize the delay performance of the selection when the options are many thousands. I noticed that until 5k options the response is very quick. I tried to insert 430k options pushing records from MySQL dataset and sadfully the select is quite unusable.
I have no problem with react-windowed but it should be very nice to handle so many options and select them, not only visualize,
so I tried with your react-windowed-select.

Thanks in advance for your answer and your time!

**Comment by jacobworrel** [comment]
@flaviodelgrosso Unfortunately, this component is only optimized up to about 10K options. This is an internal issue with how react-select builds the menu options and until that is fixed/optimized, there's nothing a windowed solution can do to mitigate this problem (see discussion [here](https://github.com/JedWatson/react-select/issues/2850#issuecomment-505980122)).

One alternative approach (that can be used in conjunction with windowing), is to only load the first n options from the dataset initially and then fetch a new filtered set of options from the server anytime the user types. Since the user is not going to scroll through a list of 430K options, there's arguably no reason for that many options to be stored in memory on the client anyway.

Hope that helps!
